version: "3"

services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_DATABASE=devops_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - 8080:80

  app:
    image: app
    container_name: application
    build: ./app
    ports:
      - 8000:8000
    volumes:
      - ./app:/app

  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - ./jenkins:/var/jenkins_home
